packages:
  - desktop
  - web-ui

ignoredBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - esbuild
  - unrs-resolver
